server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/elauso/spring-cloud-config-repo-example
          default-label: master
          clone-on-start: true
  security:
    user:
      name: root
      password: s3cr3t